info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T05:50:55.179Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-09T05:50:55.305Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T05:51:39.907Z"}
info: Connected to the database. {"timestamp":"2024-05-09T05:51:40.059Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:07:08.665Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:07:08.812Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" length must be at least 3 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:20:15.820Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:21:52.116Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:21:52.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:21:57.012Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:21:57.167Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:22:15.999Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:24:28.474Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:24:28.649Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:24:43.282Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:24:43.434Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:24:47.499Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:24:47.642Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:25:39.632Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:25:39.872Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/1 
      method - GET 
      IP - ::1
     {"timestamp":"2024-05-09T06:26:50.694Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:29:20.991Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:29:21.186Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:38:52.843Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:38:52.991Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:39:33.870Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:39:34.020Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:40:18.427Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:40:18.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:41:29.397Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:41:29.550Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:41:32.820Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:41:32.981Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:41:37.118Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:41:37.250Z"}
error: 
    status - 500 
    message - Error: Missing where attribute in the options parameter passed to findCreateFind.
    at Function.findCreateFind (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:2481:13)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:12:27)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\CPAI_Node\demo_project\src\services\/user.service.js:11:21)
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:51:36)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at newUser (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at newUserValidator (D:\CPAI_Node\demo_project\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\CPAI_Node\demo_project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:41:47.358Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:42:34.319Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:42:34.467Z"}
error: 
    status - 500 
    message - Error: Missing where attribute in the options parameter passed to findCreateFind.
    at Function.findCreateFind (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:2481:13)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:12:27)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\CPAI_Node\demo_project\src\services\/user.service.js:11:21)
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:50:36)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at newUser (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at newUserValidator (D:\CPAI_Node\demo_project\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\CPAI_Node\demo_project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:42:39.273Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:43:06.320Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:43:06.513Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:43:10.891Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:43:11.076Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:43:17.192Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:43:17.347Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:43:28.759Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:43:28.950Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:44:12.132Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:44:12.290Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:44:29.779Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:44:29.968Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:44:36.578Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:44:36.721Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:45:52.389Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:45:52.569Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:45:56.820Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:45:56.968Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:47:51.264Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:47:51.476Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:06.790Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:06.976Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:10.492Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:10.635Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:17.970Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:18.128Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:23.756Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:23.901Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:35.015Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:35.169Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:48:49.479Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:48:49.637Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:49:37.142Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:49:37.339Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:49:40.621Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:49:40.800Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:49:48.164Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:49:48.389Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:49:56.006Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:49:56.148Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:50:05.581Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:50:05.736Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:50:10.436Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:50:10.597Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:51:38.965Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:51:39.168Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:51:47.183Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:51:47.341Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:51:55.589Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:51:55.760Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:14:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:51:57.551Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:52:48.192Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:52:48.348Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:53:24.166Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:53:24.325Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:53:29.943Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:53:30.198Z"}
error: 
    status - 500 
    message - Error: User already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:14:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:53:32.198Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:56:28.083Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:56:28.258Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:56:38.139Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:56:38.287Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:56:52.820Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:56:52.963Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:57:25.373Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:57:25.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:57:37.846Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:57:41.098Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:57:41.259Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:57:54.135Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:57:54.303Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:58:03.986Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:58:04.156Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:58:09.157Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:58:09.304Z"}
error: 
    status - 500 
    message - TypeError: "flag" is read-only
    at _readOnlyError (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\readOnlyError.js:2:9)
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:19:15)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:58:20.996Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:58:52.831Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:58:53.055Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:59:00.289Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:59:15.829Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:59:16.063Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:59:19.226Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:59:50.415Z"}
info: Connected to the database. {"timestamp":"2024-05-09T06:59:50.597Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T06:59:57.293Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:00:05.552Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:00:05.727Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:00:15.111Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:01:07.865Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:01:08.048Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:01:11.905Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:01:12.051Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:01:26.107Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:01:26.292Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:01:33.461Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:01:33.613Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:03:13.506Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:03:13.672Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:03:33.440Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:03:33.620Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:03:37.051Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:03:38.320Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:07:58.387Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:07:58.546Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:08:14.654Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:08:14.804Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:08:15.274Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:09:15.288Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:09:15.462Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:09:34.542Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:09:34.719Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:09:40.485Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:09:40.679Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:09:45.792Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:09:45.964Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:10:20.566Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:10:20.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:10:55.250Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:10:55.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:11:04.665Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:11:04.807Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:05.784Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:07.356Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:10.792Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:17.616Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:11:34.993Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:11:35.139Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:38.967Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:12:14.121Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:12:14.331Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:12:35.096Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:13:01.793Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:13:01.970Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:23:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:07.056Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:13:17.320Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:13:17.554Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:13:29.280Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:13:29.428Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:13:37.668Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:13:37.825Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:13:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:51.963Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:13:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:58.555Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:16:59.564Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:16:59.729Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:17:12.752Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:17:12.964Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:17:17.421Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:17:17.569Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:17:36.646Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:17:36.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:17:44.839Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:17:44.987Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:11.894Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:12.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:24.661Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:24.808Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:29.272Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:29.448Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:43.034Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:43.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:49.059Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:49.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:18:56.139Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:18:56.352Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:19:54.347Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:19:54.514Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:19:55.767Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:19:57.972Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:20:04.905Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:20:06.537Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:21:07.371Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:21:07.538Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:21:10.321Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:21:10.482Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:24:01.279Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:24:01.445Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:24:04.675Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:24:04.832Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:24:27.937Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:24:28.087Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:24:58.539Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:24:58.716Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:19:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:25:08.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:25:41.769Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:25:41.951Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:28:42.281Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:28:42.466Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:28:50.142Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:28:50.285Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:28:54.739Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:28:54.895Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:28:57.695Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:29:05.474Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:29:53.782Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:29:53.920Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:03.045Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:30:03.199Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:06.030Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:08.714Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:30:08.895Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:13.035Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:30:13.197Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:16.953Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:17.154Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:30:17.227Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:30:33.799Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:30:33.946Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:38.288Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:41.755Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:31:19.703Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:31:19.845Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:26.093Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:27.574Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:33.565Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:42:00.367Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:42:00.553Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:46:27.704Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:46:27.858Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:47:01.405Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:47:01.560Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:47:17.433Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:47:17.581Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:47:43.721Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:47:43.870Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:47:52.417Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:47:52.560Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:47:57.561Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:47:57.726Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:04.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:07.247Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:48:07.400Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:13.284Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:48:13.430Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:21.147Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:48:21.310Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:34.273Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:48:34.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:48:40.313Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:48:40.496Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:51:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/1 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:48:54.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:49:14.058Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:49:14.262Z"}
error: 
    status - 500 
    message - TypeError: _base.error is not a constructor
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:49:19.884Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:49:51.369Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:49:51.542Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:49:55.075Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:49:55.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:50:12.573Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:50:12.719Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:50:26.193Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:50:26.340Z"}
error: 
    status - 500 
    message - Error: Please ensure that the id enter is valid ID
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:50:27.213Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:50:59.352Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:50:59.494Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:51:35.363Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:51:35.554Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:51:50.883Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:51:51.035Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:51:54.660Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:51:54.821Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:00.758Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:00.898Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:11.357Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:11.522Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:14.652Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:14.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:28.137Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:28.289Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:32.817Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:32.967Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:52:36.307Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:52:36.491Z"}
error: 
    status - 500 
    message - Error: Please ensure that the id enter is valid ID
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:52:36.518Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:53:35.590Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:53:35.760Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:53:43.085Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:53:43.245Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:53:53.793Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:53:53.961Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:53:58.894Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:53:59.090Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:54:08.759Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:54:08.900Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:55:45.271Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:55:45.420Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:55:48.266Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:55:48.513Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:56:10.701Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:56:10.878Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:56:55.244Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:56:55.431Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T07:57:12.205Z"}
info: Connected to the database. {"timestamp":"2024-05-09T07:57:12.404Z"}
error: 
    status - 500 
    message - Error: Invlid ID
    at _callee3$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:33:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - PUT 
    IP - ::1
   {"timestamp":"2024-05-09T07:59:47.887Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T08:00:36.767Z"}
info: Connected to the database. {"timestamp":"2024-05-09T08:00:37.016Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-09T08:00:44.773Z"}
info: Connected to the database. {"timestamp":"2024-05-09T08:00:45.021Z"}
