info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:17:22.606Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:17:22.762Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:18:15.988Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:18:16.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:20:53.845Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:53.876Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:20:57.733Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:57.775Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:41:22.902Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:41:22.947Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:42:23.803Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:42:23.847Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T07:44:24.738Z"}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:44:24.780Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:14:44.458Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:14:44.514Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:16:49.384Z"}
error: Could not connect to the database. Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to Mayur\\LOCALDB#BDCCF332:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:16:53.566Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:20:05.732Z"}
error: Could not connect to the database. Failed to connect to localhost:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:20:05.783Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:51:35.677Z"}
error: Could not connect to the database. Failed to connect to localhost:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:51:35.710Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:56:13.612Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:56:13.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T09:57:56.442Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:57:56.478Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:19:46.675Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:19:46.708Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:21:50.641Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:21:50.687Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:22:01.626Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:22:01.683Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:25:15.528Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:15.724Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:25:54.313Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:54.361Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:46:02.919Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:46:02.960Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:51:33.241Z"}
error: Could not connect to the database. Connection lost - Unable to process incoming packet {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Connection lost - Unable to process incoming packet\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:33.285Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:51:46.474Z"}
error: Could not connect to the database. Unknown database 'express' {"name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'express'\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:46.582Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T10:52:10.721Z"}
info: Connected to the database. {"timestamp":"2024-05-08T10:52:10.811Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:03:01.014Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:03:01.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:09:07.117Z"}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:09:07.155Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:17:36.305Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:17:36.430Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:18:07.773Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:18:07.862Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:19:14.345Z"}
error: Could not connect to the database. Failed to connect to 169.254.150.115:1433 in 15000ms {"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:19:29.380Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:20:30.152Z"}
error: Could not connect to the database. Failed to connect to 169.254.150.115:1433 in 15000ms {"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:20:45.180Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:22:25.387Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:22:25.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-05-08T11:24:22.939Z"}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:24:23.023Z"}
